# Generated by Django 3.1.2 on 2020-11-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmovies', '0002_auto_20201118_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all',
            name='section',
        ),
        migrations.AddField(
            model_name='all',
            name='section',
            field=models.ManyToManyField(to='mmovies.sections'),
        ),
    ]
