# Generated by Django 3.1.2 on 2020-11-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmovies', '0003_auto_20201118_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all',
            old_name='name',
            new_name='fullname',
        ),
        migrations.AddField(
            model_name='all',
            name='shortname',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
