# Generated by Django 3.1.2 on 2020-11-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmovies', '0005_auto_20201118_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all',
            name='shortname',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
