# Generated by Django 3.1.2 on 2020-11-20 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mmovies', '0007_all_watchlist_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all',
            name='watchlist_in',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
