# Generated by Django 3.1.2 on 2020-11-20 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmovies', '0008_auto_20201120_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_watchlist_child',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mmovies.all'),
        ),
    ]
