# Generated by Django 3.1.2 on 2020-11-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmovies', '0010_auto_20201120_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_watchlist_child',
            old_name='user',
            new_name='u',
        ),
    ]
