# Generated by Django 3.1.2 on 2020-11-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmovies', '0011_auto_20201120_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all',
            name='type',
            field=models.CharField(choices=[('Movie', 'Movie'), ('Series', 'Series')], max_length=100, null=True),
        ),
    ]
