# Generated by Django 3.1.2 on 2020-11-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmovies', '0012_auto_20201122_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('series', 'Series')], max_length=100, null=True),
        ),
    ]
